### ISSUE TITLE
User-level deps.edn is in a different place on XDG systems

### ISSUE THREAD

**Issue by seancorfield** [practicalli/clojure-deps-edn#14]
I've just updated some of my repos to note that the user-level `deps.edn` file is in `~/.config/clojure/` on some systems (the deps/CLI reference notes them as "Freedesktop conventions"). This seems to be where the `XDG_CONFIG` environment variable points on such systems (and that takes precedence over the `HOME` variable in `clojure` shell script, if `CLJ_CONFIG` is not set).

Just in case you want to add a note in your repo.

**Comment by jr0cket** [comment]
I experienced this a couple of weeks ago and added it to the install section.

https://github.com/practicalli/clojure-deps-edn#install-practicalli-clojure-deps-edn

Debian Linux was the OS involved, it does follow all these type of standards.  I actually like this standard, but it doesn't seem that widely applied yet.  Hopefully Ubuntu and MacOSX will adopt this setting too.

Sorry, I should have also let you know at that time about this.
