### ISSUE TITLE
Rewrite hot-load documentation to match changes

### ISSUE THREAD

**Issue by gtoast** [practicalli/clojure-deps-edn#18]
[Per the changes referenced in this issue](https://github.com/practicalli/clojure-content/issues/376#issue-806873135), with your approval, I'd like to work on a pull request to change the documentation and language in your deps.edn to reflect changes to the hot-load alias.

**Comment by practicalli-john** [comment]
The README and deps.edn files have been updated to link to the hotload documentation in Practicalli Clojure.

Thank you.
