### ISSUE TITLE
Broken link (updating)

### ISSUE THREAD

**Issue by seancorfield** [practicalli/clojure-deps-edn#2]
Currently, `Updating practicalli/clojure-deps-edn` links to `https://github.com/practicalli/clojure-deps-edn/blob/live/updating-practicalli/clojure-deps-edn` which does not exist.

It looks like it should link to `updating-practicalliclojure-deps-edn` (without the `/`).

**Comment by jr0cket** [comment]
Yes, good catch.  The / on the title is dropped when GitHub adds the Id

As the full URL in the rendered page is
https://github.com/practicalli/clojure-deps-edn#updating-practicalliclojure-deps-edn

I think changing the title by using a space instead of / will make a nicer Id name
