### ISSUE TITLE
Change of user-config to config-user

### ISSUE THREAD

**Issue by samusz** [practicalli/clojure-deps-edn#20]
'user-config' is now 'config-user'

`samusz@CESP-176-39 polylithExample % clojure -Sdescribe

{:version "1.10.3.833"
 :config-files ["/usr/local/Cellar/clojure/1.10.3.833/deps.edn" "/Users/samusz/.clojure/deps.edn" "deps.edn" ]
 :config-user "/Users/samusz/.clojure/deps.edn"
 :config-project "deps.edn"
 :install-dir "/usr/local/Cellar/clojure/1.10.3.833"
 :config-dir "/Users/samusz/.clojure"
 :cache-dir ".cpcache"
 :force false
 :repro false
 :main-aliases ""
 :repl-aliases ""}`

**Comment by practicalli-john** [comment]
Pull request merged, thank you.

**Comment by samusz** [comment]
@practicalli-john Thank you for all your open and free work out here ! Best.
