### ISSUE TITLE
:test/eftest runner hangs when finished

### ISSUE THREAD

**Issue by camsaul** [practicalli/clojure-deps-edn#22]
After running a test suite and reporting the failures it just hangs until you kill the process. `eftest.runner/run-tests` is intended for REPL usage and returns a map with a summary and doesn't initiate shutdown. If you look at the source for `lein-eftest` it checks the number of failures/errors returned by `run-tests` and exits with nonzero if they are nonzero -- see https://github.com/weavejester/eftest/blob/master/lein-eftest/src/leiningen/eftest.clj#L83-L116

**Comment by practicalli-john** [comment]
The eftest alias is a hack to make it work.  Unless there is a better approach, I will deprecate this alias.

Cognitect Labs and Kaocha both support running with Clojure CLI tools and are easy to configure.

Thank you for highlighting this issue.
