### ISSUE TITLE
Accidentally removed "clone" from git installation command in README

### ISSUE THREAD

**Issue by KingMob** [practicalli/clojure-deps-edn#42]
In the recent change below, `clone` was removed, so this isn't a valid git command any more. Also, I don't know if it's just me or all Mac users, but $XDG_CONFIG_HOME isn't set at all, FWIW.

```diff
- git clone your-fork-url ~/.clojure/
+ git git@github.com:practicalli/clojure-deps-edn.git $XDG_CONFIG_HOME/clojure
```

**Comment by practicalli-john** [comment]
Updated the readme, thank you.
