### ISSUE TITLE
Windows and Clojure CLI - escape character issues

### ISSUE THREAD

**Issue by watchtheblur** [practicalli/clojure-deps-edn#44]
Currently the readme.md says to execute: `clojure -X:deps mvn-install project.jar`

The result I get is:
`Key is missing value: project.jar`

When I execute `clojure -X:deps mvn-install :jar project.jar` I get
```
my-library $ clojure -X:deps mvn-install :jar "project.jar"
Installing project.jar
Execution error (IllegalArgumentException) at clojure.tools.cli.api/read-pom-in-jar (api.clj:310).
No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.Symbol
```

**Comment by practicalli-john** [comment]
Apologies, the `:jar` value should be wrapped in single and double quotes when called on the command line.  The single quotes ensure the shell passed the value as a string to the `clojure` command.

```sh
clojure -X:deps mvn-install :jar '"project.jar"'
``` 

I'll update any documentation where this is not clearly defined.  Thank you.

**Comment by watchtheblur** [comment]
I'm still getting the same error after wrapping single quotes:

```
my-library $ clojure -X:deps mvn-install :jar '"project.jar"'
Installing project.jar
Execution error (IllegalArgumentException) at clojure.tools.cli.api/read-pom-in-jar (api.clj:310).
No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.Symbol
```

Is it possible to indicate the path to the jar in either deps.edn or pom.xml so that we can bypass the quoting issue?

**Comment by practicalli-john** [comment]
The `:deps` alias is built into the Clojure CLI tool, so I am unsure if default values can be specified through `:exec-args`, as done with custom aliases.

My assumption is the shell used is removing the single and double quotes, although this is unusual.  If it is a Windows command terminal or powershell, then that could be the cause.

I assume there could be an issue with the pom.xml file used to help generate the jar.  Can you share the project and details of Operating System, which version of Clojure CLI being used (`clojure -Sdescribe`) and tool used to build the jar.

I can successfully deploy a jar that was built with depstar on Ubuntu Linux, using zsh.

I'll investigate and see if I can find similar issues.

**Comment by practicalli-john** [comment]
The `:deps` alias is built into the Clojure CLI tool, so I am unsure if default values can be specified through `:exec-args`, as done with custom aliases.

My assumption is the shell used is removing the single and double quotes, although this is unusual.  If it is a Windows command terminal or powershell, then that could be the cause.

I assume there could be an issue with the pom.xml file used to help generate the jar.  Can you share the project and details of Operating System, which version of Clojure CLI being used (`clojure -Sdescribe`) and tool used to build the jar.

I can successfully deploy a jar that was built with depstar on Ubuntu Linux, using zsh.

I'll investigate and see if I can find similar issues.

**Comment by practicalli-john** [comment]
The only similar issues I found were due to the interesting way that windows escapes characters

In summary, If using Windows, try Powershell rather than CMD.exe and use backslashes and/or backticks to escape the double quotes, or single quotes wrapping 3 pairs of double quotes

```sh
clojure -X:deps mvn-install :jar `"project.jar"`
clojure -X:deps mvn-install :jar \"project.jar\"
clojure -X:deps mvn-install :jar \`"project.jar\`"
clojure -X:deps mvn-install :jar '"""project.jar"""'
```

> I am afraid I can't test these as I do not have windows, but these are approaches mentioned in the #clj-on-windows slack channel

The other alternative would be to install Windows for Linux subsystem (if the version of Windows supports it).  Then the Clojure command can be run in a Unix environment where escaping rules are better understood in general and seem much more consistent.

**Comment by practicalli-john** [comment]
From https://clojure.org/reference/deps_and_cli#quoting

... on cmd.exe or Powershell, additional escape quoting is required for string values. Unfortunately the combination of quoting rules for converting command line Windows program arguments and Powershell quoting and word splitting are very complicated.

To pass a string value at the top level, if the string value does not have spaces, you can use `'\"str\"'`. If the string value does have spaces (or not) you should use `'"""str value"""'`.

```
PS D:> clj -X clojure.core/prn :string1 '\"no-spaces\"' :string2 '"""has spaces"""'
{:string1 "no-spaces", :string2 "has spaces"}
```

For string values nested inside other collections, use double quotes if there are spaces and triple quotes if there are not:

```
PS D:> clj -X clojure.core/prn :val '{:s1 """nospaces""" :s2 ""has spaces""}'
{:val {:s1 "nospaces", :s2 "has spaces"}}
```

**Comment by watchtheblur** [comment]
I am indeed on Windows (Clojure CLI version 1.11.1.1105), and did try many combinations of quoting, but only your examples worked for me.     The 2 that works specifically are:

```
clojure -X:deps mvn-install :jar \`"project.jar\`"
clojure -X:deps mvn-install :jar '"""project.jar"""'
```

Perhaps there's a way to indicate the location of the `project.jar` file in deps.edn so that running commands like:
 `clojure -X:deps mvn-pom` 
would generate the correct pom.xml to run `mvn-install` without arguments?  I tried to figure that out myself before creating this issue but wasn't able to figure it out.

Either way, Thanks for looking into this!  I really appreciate this repo and all the work you've done!  I'll leave this open in case you decide to help other windows folks by updating the readme.  But I'd understand if that's out of scope.
