### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by respatialized** [practicalli/clojure-deps-edn#45]
Hi, @practicalli-john -

Thanks for making all these useful aliases available to the Clojure community. I think it might be helpful for myself and others if you clarified what license you're making this project available under, as there currently doesn't seem to be a license as far as I can tell.

**Comment by practicalli-john** [comment]
All Practicalli content should be licensed under Creative commons.  I've added license details to the readme and will check other Practicalli works to ensure the license is specified. 

Thank you.
