### ISSUE TITLE
:mvn/local-repo appears to be broken as it is relative

### ISSUE THREAD

**Issue by shay-rf** [practicalli/clojure-deps-edn#48]
The :mvn/local-repo was changed  to  ".cache/maven/repository" which is relative ( this probably should be absolute path in $HOME/ )
It appears to break the existing usage.
I commented it out for now - to default back to ~/.m2

**Comment by practicalli-john** [comment]
Yes, it seems it is relative to the path the command is run in the terminal and `~` or environment variables are not resolved.

I've comment out this setting with an appropriate example using a full path, and will push an update.
