### ISSUE TITLE
Error when using :search/outdated

### ISSUE THREAD

**Issue by colliderwriter** [practicalli/clojure-deps-edn#51]
Latest clojure, latest clojure-deps-edn.

```
$ clojure -T:search/outdated
No function found on command line or in :exec-fn
```

```
$ clojure -version
Clojure CLI version 1.11.1.1149
```

```
$ cd ~/.clojure
[collider@grabber .clojure]$ git status 
On branch live
Your branch is up to date with 'origin/live'.

nothing to commit, working tree clean
```

**Comment by practicalli-john** [comment]
Curious, I used that alias a couple of days ago to update libraries.  I'll check again today 

Can you run `clojure -Sdescribe` and paste the results in a comment here.

This command should include the user level deps.edn file on the path
Thank you

**Comment by practicalli-john** [comment]
I've updated to Clojure CLI version 1.11.1.1149 and the `:search/outdated` alias is still working correctly.  This version of Clojure CLI was tested on MacOXS and will be tested on Linux later today.

The `:search/outdated` alias can also be run using the -X execution option
```
clojure -X:search/outdated
```

To check if other aliases are affected with the same issue, try one or more of these
```
clojure -T:project/new
clojure -T:graph/deps
```

The Clojure CLI version 1.11.1.1149 was released about 18 hours ago, if it was installed before that time there may have been a bug as part of the pre-release (but I assume that would have been an earlier number).

Finally, all commands are being tested on Java 17.  If using a different version, please state the version used.

Thank you.

**Comment by colliderwriter** [comment]
Upon further investigation, it was a location issue due to XDG_CONFIG_HOME unexpectedly being used. 

Apologies for the time wasted.

Closing.
